### PR TITLE
Expose cython API for external use

### PR DESCRIPTION
**Pull request by kylebarron**
### Change list

- Update `CMakeLists.txt` to include `.pyx` and `.pxd` files in distribution after skbuild is done processing
- Include `h3api.h` in final bundle. This can usually be found automatically when compiling, but if we have issues with this in the future, we can emulate Numpy and its [`np.get_include` function](https://numpy.org/devdocs/reference/generated/numpy.get_include.html). 
- Add test that uses the external Cython API.

Closes https://github.com/uber/h3-py/issues/152

### CODE REVIEW

**Comment by kylebarron** [comment]
Ah the test script in cibuildwheel needs to be updated to either ignore the Cython test or compile the cython file used in that test.

**Comment by kylebarron** [comment]
I updated to ignore the test when the cython example wasn't compiled

**Review by ajfriend — APPROVED** [review]

**Comment by ajfriend** [comment]
Sweeeeeeet!

**Comment by ajfriend** [comment]
Really simple notebook example for future reference: https://gist.github.com/ajfriend/167afffde74bc08b0e809e10b92ecde3

**Pull request merged**
