### PR TITLE
Moved cython tests to own folder

### LINKED ISSUE #346: Move cython test to its own folder
Move `test_cython.py` and `cython_example.pyx` to a separate folder.

### PR DESCRIPTION
**Pull request by I3lackRacer**
Moved cython_example.pyx and test_cython.py tests to their own folder

Closes #346

### CODE REVIEW

**Comment by ajfriend** [comment]
I think you'll also need to update the `makefile` and the `test.yml`

**Comment by ajfriend** [comment]
Looks good. We just need the CLA to be signed.

**Comment by I3lackRacer** [comment]
Do i have to do something for the CLA to be signed (beside the form which i filled out)

**Comment by ajfriend** [comment]
Hmmm. If you've already signed it, maybe it is just taking some time to register. I can check back by tomorrow.

**Comment by isaacbrodsky** [comment]
I've seen issues with the CLA before if there is a mismatch between the email used on the commit and the email (or account) used to sign. Could you confirm the emails are the same? There should be very little lag between signing and the check going green

**Review by isaacbrodsky — APPROVED** [review]

**Review by dfellis — APPROVED** [review]

**Comment by ajfriend** [comment]
I just ran locally and noticed one more thing. Can you update the `.gitignore` line that currently has `tests/*.c`

**Review by ajfriend — CHANGES_REQUESTED** [review]
Can you update the .gitignore line that currently has tests/*.c

**Comment by I3lackRacer** [comment]
Good idea. All *.c files in tests/ and subfolders will now be ignored

**Review by ajfriend — APPROVED** [review]
Thanks!

**Pull request merged**
