### PR TITLE
Add `MANIFEST.in` file for smaller sdist

### PR DESCRIPTION
**Pull request by kylebarron**
By adding a `MANIFEST.in` file, we can exclude files not necessary to build. This reduces the sdist size from 17MB to 198KB.

You can test that this sdist covers the necessary files by installing from this sdist in a new virtualenv (note that I don't think this is actually tested right now in CI, that you can actually install from the sdist):

```
> pipx run build --sdist
> virtualenv test_env
> source ./test_env/bin/activate
> pip install dist/h3-3.7.3.tar.gz
Processing ./dist/h3-3.7.3.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: h3
  Building wheel for h3 (pyproject.toml) ... done
  Created wheel for h3: filename=h3-3.7.3-cp38-cp38-macosx_11_0_x86_64.whl size=690776 sha256=411c0831a2e966d139437d08712d97774c15b94e7c9960ebe45da4fa5455ab80
  Stored in directory: /Users/kbarron/Library/Caches/pip/wheels/de/7a/ec/181fcd0e08c7df8d1d6c52575ed2b2d61e42fbe7bb7cf1c2b0
Successfully built h3
Installing collected packages: h3
Successfully installed h3-3.7.3
```

Here's the full list of files copied into the sdist:

<details>

```
copying CHANGELOG.md -> h3-3.7.3
copying CMakeLists.txt -> h3-3.7.3
copying LICENSE -> h3-3.7.3
copying dev_notes.md -> h3-3.7.3
copying makefile -> h3-3.7.3
copying pyproject.toml -> h3-3.7.3
copying readme.md -> h3-3.7.3
copying requirements.in -> h3-3.7.3
copying setup.py -> h3-3.7.3
copying src/h3/CMakeLists.txt -> h3-3.7.3/src/h3
copying src/h3/__init__.py -> h3-3.7.3/src/h3
copying src/h3/_cy.pyx -> h3-3.7.3/src/h3
copying src/h3/_version.py -> h3-3.7.3/src/h3
copying src/h3.egg-info/PKG-INFO -> h3-3.7.3/src/h3.egg-info
copying src/h3.egg-info/SOURCES.txt -> h3-3.7.3/src/h3.egg-info
copying src/h3.egg-info/dependency_links.txt -> h3-3.7.3/src/h3.egg-info
copying src/h3.egg-info/requires.txt -> h3-3.7.3/src/h3.egg-info
copying src/h3.egg-info/top_level.txt -> h3-3.7.3/src/h3.egg-info
copying src/h3/_cy/CMakeLists.txt -> h3-3.7.3/src/h3/_cy
copying src/h3/_cy/__init__.py -> h3-3.7.3/src/h3/_cy
copying src/h3/_cy/api.pxd -> h3-3.7.3/src/h3/_cy
copying src/h3/_cy/api.pyx -> h3-3.7.3/src/h3/_cy
copying src/h3/_cy/cells.pyx -> h3-3.7.3/src/h3/_cy
copying src/h3/_cy/edges.pyx -> h3-3.7.3/src/h3/_cy
copying src/h3/_cy/geo.pyx -> h3-3.7.3/src/h3/_cy
copying src/h3/_cy/h3lib.pxd -> h3-3.7.3/src/h3/_cy
copying src/h3/_cy/to_multipoly.pyx -> h3-3.7.3/src/h3/_cy
copying src/h3/_cy/unstable_vect.pyx -> h3-3.7.3/src/h3/_cy
copying src/h3/_cy/util.pxd -> h3-3.7.3/src/h3/_cy
copying src/h3/_cy/util.pyx -> h3-3.7.3/src/h3/_cy
copying src/h3/api/__init__.py -> h3-3.7.3/src/h3/api
copying src/h3/api/_api_template.py -> h3-3.7.3/src/h3/api
copying src/h3/api/basic_int/__init__.py -> h3-3.7.3/src/h3/api/basic_int
copying src/h3/api/basic_int/_binding.py -> h3-3.7.3/src/h3/api/basic_int
copying src/h3/api/basic_int/_public_api.py -> h3-3.7.3/src/h3/api/basic_int
copying src/h3/api/basic_str/__init__.py -> h3-3.7.3/src/h3/api/basic_str
copying src/h3/api/basic_str/_binding.py -> h3-3.7.3/src/h3/api/basic_str
copying src/h3/api/basic_str/_public_api.py -> h3-3.7.3/src/h3/api/basic_str
copying src/h3/api/memview_int/__init__.py -> h3-3.7.3/src/h3/api/memview_int
copying src/h3/api/memview_int/_binding.py -> h3-3.7.3/src/h3/api/memview_int
copying src/h3/api/memview_int/_public_api.py -> h3-3.7.3/src/h3/api/memview_int
copying src/h3/api/numpy_int/__init__.py -> h3-3.7.3/src/h3/api/numpy_int
copying src/h3/api/numpy_int/_binding.py -> h3-3.7.3/src/h3/api/numpy_int
copying src/h3/api/numpy_int/_public_api.py -> h3-3.7.3/src/h3/api/numpy_int
copying src/h3/unstable/__init__.py -> h3-3.7.3/src/h3/unstable
copying src/h3/unstable/v4.py -> h3-3.7.3/src/h3/unstable
copying src/h3/unstable/vect.py -> h3-3.7.3/src/h3/unstable
copying src/h3lib/CMakeLists.txt -> h3-3.7.3/src/h3lib
copying src/h3lib/LICENSE -> h3-3.7.3/src/h3lib
copying src/h3lib/README.md -> h3-3.7.3/src/h3lib
copying src/h3lib/VERSION -> h3-3.7.3/src/h3lib
copying src/h3lib/cmake/Config.cmake.in -> h3-3.7.3/src/h3lib/cmake
copying src/h3lib/cmake/TestWrapValgrind.cmake -> h3-3.7.3/src/h3lib/cmake
copying src/h3lib/cmake/toolchain.cmake -> h3-3.7.3/src/h3lib/cmake
copying src/h3lib/src/h3lib/include/algos.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/alloc.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/baseCells.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/bbox.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/constants.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/coordijk.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/faceijk.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/geoCoord.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/h3Index.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/h3UniEdge.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/h3api.h.in -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/linkedGeo.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/localij.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/mathExtensions.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/polygon.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/polygonAlgos.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/vec2d.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/vec3d.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/vertex.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/include/vertexGraph.h -> h3-3.7.3/src/h3lib/src/h3lib/include
copying src/h3lib/src/h3lib/lib/algos.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
copying src/h3lib/src/h3lib/lib/baseCells.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
copying src/h3lib/src/h3lib/lib/bbox.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
copying src/h3lib/src/h3lib/lib/coordijk.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
copying src/h3lib/src/h3lib/lib/faceijk.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
copying src/h3lib/src/h3lib/lib/geoCoord.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
copying src/h3lib/src/h3lib/lib/h3Index.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
copying src/h3lib/src/h3lib/lib/h3UniEdge.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
copying src/h3lib/src/h3lib/lib/linkedGeo.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
copying src/h3lib/src/h3lib/lib/localij.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
copying src/h3lib/src/h3lib/lib/mathExtensions.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
copying src/h3lib/src/h3lib/lib/polygon.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
copying src/h3lib/src/h3lib/lib/vec2d.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
copying src/h3lib/src/h3lib/lib/vec3d.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
copying src/h3lib/src/h3lib/lib/vertex.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
copying src/h3lib/src/h3lib/lib/vertexGraph.c -> h3-3.7.3/src/h3lib/src/h3lib/lib
```

</details>

Closes https://github.com/uber/h3-py/issues/125

If you'd like to test out the sdist, this is the file created from my computer: [h3-3.7.3.tar.gz](https://github.com/uber/h3-py/files/8468898/h3-3.7.3.tar.gz)

### CODE REVIEW

**Comment by ajfriend** [comment]
Awesome! Could you add a job for running the test suite from the sdist? Debatable, but it might be nice to run it across each of win/max/linux.

**Comment by kylebarron** [comment]
@ajfriend Do you happen to know if there are other system requirements for building h3 that I'm missing and that's causing this CI to fail? https://github.com/uber/h3-py/runs/5993418571?check_suite_focus=true

**Comment by ajfriend** [comment]
> @ajfriend Do you happen to know if there are other system requirements for building h3 that I'm missing and that's causing this CI to fail? https://github.com/uber/h3-py/runs/5993418571?check_suite_focus=true

I think you need to pip install:

scikit-build
cython
cmake

**Comment by kylebarron** [comment]
I'll try that, but I thought that would've been covered by [`Installing build dependencies: finished with status 'done'`](https://github.com/uber/h3-py/runs/5993418571?check_suite_focus=true#step:4:73) since those are defined in the `pyproject.toml`, and the `pyproject.toml` is included in the sdist

**Comment by ajfriend** [comment]
> I'll try that, but I thought that would've been covered by [`Installing build dependencies: finished with status 'done'`](https://github.com/uber/h3-py/runs/5993418571?check_suite_focus=true#step:4:73) since those are defined in the `pyproject.toml`, and the `pyproject.toml` is included in the sdist

And a `pip install --upgrade pip setuptools wheel` might also be worth a try.

**Comment by ajfriend** [comment]
Hmm. Does it work without the manifest and setup.py changes?

**Comment by kylebarron** [comment]
> Hmm. Does it work without the manifest and setup.py changes?

Let's see: https://github.com/uber/h3-py/pull/228

**Comment by kylebarron** [comment]
Ok so presumably I'm missing a couple necessary files here

**Comment by kylebarron** [comment]
With a little bit of trial and error, it looks like `h3lib/src/apps/*` was required. I'm guessing that the default h3 build config builds _everything_ and so it errored when it wasn't able to find that directory. I had wrongly assumed that we only needed `src/h3lib/src/h3lib`

**Review by ajfriend — APPROVED** [review]

**Pull request merged**
