### PR TITLE
CI test that sdist can be installed

### PR DESCRIPTION
**Pull request by kylebarron**

### CODE REVIEW

**Comment by kylebarron** [comment]
Interesting that the sdist test passes here.

**Comment by ajfriend** [comment]
Can we also run the tests after the sdist install? In this and #227

**Comment by kylebarron** [comment]
Seems easiest to just install from sdist in the tests

**Comment by kylebarron** [comment]
We might as well merge this first and then update #227 from the master branch

**Comment by ajfriend** [comment]
I like the idea of testing both install methods. Could you leave the `tests.yml` as it was? And then add the tests after building the sdist in `wheels.yml`?

I like that logical separation a bit better. That way, we're treating the sdist as just another "distribution" along with the wheels, and by adding the tests, we're testing them the same (since cibuildwheel runs the tests after building the wheel).

**Comment by ajfriend** [comment]
Closed by #229

**Pull request closed without merging**
