### PR TITLE
Fix sdist build

### PR DESCRIPTION
**Pull request by ajfriend**

### CODE REVIEW

**Comment by ajfriend** [comment]
@isaacbrodsky just added a makefile target that reproduces the issue locally

**Comment by ajfriend** [comment]
So even tho the `sdist` build and install seems to run fine in github actions, I'm still having issues getting it working on my mac laptop.

I'm getting the following error: 

```
CMake Error: File /private/var/folders/p9/gc1qcwtx6wg5_22cf88gcqlh0000gn/T/pip-req-build-132zpnc8/src/h3lib/dev-docs/Doxyfile.in does not exist.
      CMake Error at src/h3lib/CMakeLists.txt:355 (configure_file):
        configure_file Problem configuring file
```

I get that if I run `make sdist` from the makefile in this repo, or if I try installing from the github actions build artifact file.

Not sure what's different between the github actions environment and my laptop. @isaacbrodsky, do you know what's going on here?

**Comment by ajfriend** [comment]
Still have this issue when running locally, even tho the github macos action seems to work here.

https://gist.github.com/ajfriend/ba66e9169606d983ed9d935b8658a160

**Comment by ajfriend** [comment]
Ready for review. Going to fix up the sdist build a bit more in a fast follow up PR.

**Review by isaacbrodsky — APPROVED** [review]

**Pull request merged**
