### PR TITLE
Add python 3.12 wheels on v3.7

### PR DESCRIPTION
**Pull request by msaecker**
Extend the exisiting build pipeline to create python 3.12 wheels.

### CODE REVIEW

**Comment by isaacbrodsky** [comment]
This does not seem to be building correctly? https://github.com/uber/h3-py/actions/runs/8047484474/job/22005886719?pr=344

**Comment by msaecker** [comment]
> This does not seem to be building correctly? https://github.com/uber/h3-py/actions/runs/8047484474/job/22005886719?pr=344

Yeah, the cibuildwheel version did not support python 3.12 yet. I upgraded to the newest one. The earliest stable ABI was in version 2.15, with the final CPython 3.12 in v2.16.2.

**Comment by msaecker** [comment]
I cherry-picked some commits from main dropping c1 builds and python 2.7 & 3.5. I also added a commit dropping 3.6.

**Comment by msaecker** [comment]
The cherry-picking seems to have overwritten the cibuildversion to 2.16.2 instead of 2.16.5, but that should be fine as it contains a final CPython version for 3.12. I have no idea why the windows build failed and this is as far as I am taking this PR.

**Comment by msaecker** [comment]
Upgraded cibuildwheel back to 2.16.5 as this might be the cause of the windows build issues.

**Comment by msaecker** [comment]
All green.

**Comment by ajfriend** [comment]
This looks good. Thanks @msaecker!

**Review by ajfriend — APPROVED** [review]

**Pull request merged**
